FROM docker.io/golang:1.25-alpine AS builder

WORKDIR /app
COPY testing/containers/mock-origin/* ./
RUN CGO_ENABLED=0 GOOS=linux go build -o mock-origin main.go

FROM docker.io/alpine:latest AS run

COPY --from=builder /app/mock-origin /usr/local/bin/mock-origin

EXPOSE 8080

CMD ["mock-origin"]
