FROM docker.io/caddy:2.11.4-builder-alpine AS builder

COPY ./ /opt/caddy-cache

RUN xcaddy build \
    --with github.com/dotvezz/mak-cache/plugins/caddy=/opt/caddy-cache/plugins/caddy

FROM docker.io/caddy:2.11.4-alpine AS run

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
