name: caddy-cache testing stack

services:
  caddy:
    build:
      context: ../../
      dockerfile: testing/containers/caddy/Containerfile
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8081:8080
      - 2021:2020

  caddy-e2e:
    build:
      context: ../../
      dockerfile: testing/containers/caddy/Containerfile
    volumes:
      - ./e2e/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8086:8080
      - 2022:2020

  caddy-e2e-valkey:
    build:
      context: ../../
      dockerfile: testing/containers/caddy/Containerfile
    depends_on:
      - valkey
    volumes:
      - ./e2e-valkey/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8087:8080
      - 2023:2020

  mock-origin:
    build:
      context: ../../
      dockerfile: testing/containers/mock-origin/Containerfile
    volumes:
      - ../mock-responses:/srv:ro
    ports:
      - 8085:8080

  caddy-souin:
    build:
      context: ../../
      dockerfile: testing/containers/caddy-souin/Containerfile
    volumes:
      - ./caddy-souin/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8082:8082
      - 2020:2019

  fileserver:
    image: docker.io/caddy:2.11.4-alpine
    volumes:
      - ./fileserver/Caddyfile:/etc/caddy/Caddyfile
      - ../files:/srv:ro
    ports:
      - 8084:80

  varnish:
    image: docker.io/varnish:fresh
    environment:
      VARNISH_SIZE: 768M
      VARNISH_HTTP_PORT: 8083
    tmpfs:
      - /var/lib/varnish:exec
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl:ro
    ports:
      - "8083:8083"
    command:
      - -p
      - thread_pools=8
      - -p
      - thread_pool_min=500
      - -p
      - thread_pool_max=5000
      - -p
      - feature=-http2

  valkey:
    image: docker.io/valkey/valkey:9.1-alpine
    ports:
      - "6379:6379"
