name: caddy-cache testing stack

services:
  # The test container for caddy-cache with otter
  caddy-otter:
    build:
      context: ../../
      dockerfile: testing/containers/caddy/Containerfile
    volumes:
      - ./e2e/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8086:8080
      - 2022:2020

  # The test container for caddy-cache with valkey
  caddy-valkey:
    build:
      context: ../../
      dockerfile: testing/containers/caddy/Containerfile
    depends_on:
      - valkey
    volumes:
      - ./e2e-valkey/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8087:8080
      - 2023:2020

  # the valkey container, as a dep for caddy-valkey
  valkey:
    image: docker.io/valkey/valkey:9.1-alpine
    ports:
      - "6379:6379"

  # The test container for souin with otter (the only souin source, we're not testing with any other storages)
  caddy-souin:
    build:
      context: ../../
      dockerfile: testing/containers/caddy-souin/Containerfile
    volumes:
      - ./caddy-souin/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8082:8082
      - 2020:2019

  # the test container for varnish's default configuration.
  varnish:
    image: docker.io/varnish:fresh
    depends_on:
      - mock-origin
      - fileserver
    environment:
      VARNISH_SIZE: 8G
      VARNISH_HTTP_PORT: 8083
    tmpfs:
      - /var/lib/varnish:exec
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl:ro
    ports:
      - "8083:8083"
    command:
      - -p
      - thread_pools=4
      - -p
      - thread_pool_min=100
      - -p
      - thread_pool_max=1000
      - -p
      - workspace_client=128k
      - -p
      - listen_depth=4096
      - -p
      - feature=-http2

  # The origin container for e2e tests, providing a variety of mock responses
  mock-origin:
    build:
      context: ../../
      dockerfile: testing/containers/mock-origin/Containerfile
    volumes:
      - ../mock-responses:/srv:ro
      - ../files:/srv/GET/file:ro
    ports:
      - 8085:8080

  # the origin container for benchmarking caches, a simple fileserver with files of varying sizes and types
  fileserver:
    image: docker.io/caddy:2.11.4-alpine
    volumes:
      - ./fileserver/Caddyfile:/etc/caddy/Caddyfile
      - ../files:/srv:ro
    ports:
      - 8084:80
